[package]
name = "whatyoumean"
version = "1.1.2"
edition = "2021"
description = "A CLI dictionary"
license = "GPL-3.0"
authors = ["Clayman"]
readme = "README.md"
repository = "https://github.com/Clay-6/WhatYouMean"
keywords = ["language", "definitions", "dictionary"]
categories = ["command-line-utilities"]

[[bin]]
name = "wym"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
colored = "2.0.0"
reqwest = { version = "0.11.10", features = ["json"] }
serde_json = "1.0.81"
tokio = { version = "1.18.2", features = ["full"] }
