[package]
name = "whatyoumean"
version = "3.0.0"
edition = "2021"
description = "A CLI dictionary"
license = "GPL-3.0"
authors = ["Clay66"]
readme = "README.md"
repository = "https://github.com/Clay-6/WhatYouMean"
keywords = ["language", "definitions", "dictionary"]
categories = ["command-line-utilities"]

[[bin]]
name = "wym"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
color-eyre = "0.6.2"
owo-colors = "3.5.0"
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.23.0", features = ["full"] }
