[package]
name = "whatyoumean"
version = "2.0.0"
edition = "2021"
description = "A CLI dictionary"
license = "GPL-3.0"
authors = ["Clayman"]
readme = "README.md"
repository = "https://github.com/Clay-6/WhatYouMean"
keywords = ["language", "definitions", "dictionary"]
categories = ["command-line-utilities"]

[[bin]]
name = "wym"
path = "src/main.rs"

[dependencies]